seed: 42

name: "Supervised_{data_dataset_name}_{backbone_name}_4GPU" 
artifacts_root: "artifacts/pretrain_lightly/supervised"

backbone:
  name: "resnet50" # "resnet18" / "convnextv2_pico" / "convnextv2_tiny" / "resnext50_32x4d"
  pretrained_weights: null # "imagenet" / null 
  use_batch_norm: False
  kwargs: {}
data:
  dataset_name: "imagenet-1k"
  num_workers: 16

trainer:
  max_epochs: 201
  devices: "auto"
  accelerator: "gpu"
  precision: "bf16"
  accumulate_grad_batches: null # 4
  overfit_batches: 0.0 # 1 / 0.0

optimizer:
  batch_size: 512
  lr: 0.001
  weight_decay: 0.01

wandb: true # set to false to disable wandb logging

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .